// <auto-generated />
using CarsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsApi.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20230313212748_Dataseed")]
    partial class Dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarsApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            color = "Bronze",
                            make = "Mazda",
                            model = "mazda-2",
                            price = 150000.0,
                            year = 2015
                        },
                        new
                        {
                            Id = 6,
                            color = "Yellow",
                            make = "Toyota",
                            model = "Campry",
                            price = 50000.0,
                            year = 2002
                        },
                        new
                        {
                            Id = 7,
                            color = "Red",
                            make = "BMW",
                            model = "X6",
                            price = 500000.0,
                            year = 2019
                        },
                        new
                        {
                            Id = 8,
                            color = "White",
                            make = "Mercedes",
                            model = "A200",
                            price = 900000.0,
                            year = 2020
                        },
                        new
                        {
                            Id = 9,
                            color = "Grey",
                            make = "Audi",
                            model = "A3",
                            price = 500000.0,
                            year = 2019
                        },
                        new
                        {
                            Id = 10,
                            color = "Blue",
                            make = "Audi",
                            model = "S3",
                            price = 1500000.0,
                            year = 2023
                        });
                });

            modelBuilder.Entity("CarsApi.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "adm1n",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "passw01d",
                            UserName = "User2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
